# Generated by /wiki-query — run with: python wiki/assets/meta-ad-fraud-chart.py
"""
Meta's internal 2024 estimates of scam-ad-linked revenue vs. its stated
willingness to spend remediating suspicious advertisers.

Sources:
- $16B (~10% of 2024 revenue): Reuters investigation, via
  wiki/sources/reuters-meta-fraud-profit-investigation.md
- $7B/yr "high risk" categories (= $3.5B / 6 months): same source, also cited
  in wiki/sources/cfa-lawsuit-meta-scam-ads-2026.md
- $3B China-linked scam/banned-product revenue (out of $18B China ad revenue):
  wiki/sources/reuters-meta-fraud-profit-investigation.md
- $135M willingness to sacrifice to address suspicious advertisers:
  wiki/sources/reuters-meta-fraud-profit-investigation.md
"""
import matplotlib.pyplot as plt

labels = [
    "Projected 2024 revenue\nfrom scam/banned-goods ads\n(~10% of total)",
    "Annualized revenue from\n\"high risk\" ad categories",
    "China-linked scam/banned-\nproduct ad revenue (2024)",
    "Revenue Meta would sacrifice\nto address suspicious advertisers",
]
values_billion = [16, 7, 3, 0.135]
colors = ["#c0392b", "#e67e22", "#e67e22", "#27ae60"]

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(labels, values_billion, color=colors)
ax.set_ylabel("USD (billions, log scale)")
ax.set_yscale("log")
ax.set_title("Meta's Internal 2024 Estimates: Scam-Ad Revenue vs. Remediation Spend")

for bar, val in zip(bars, values_billion):
    label = f"${val:g}B" if val >= 1 else f"${val * 1000:.0f}M"
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() * 1.15, label,
            ha="center", va="bottom", fontsize=10)

plt.xticks(rotation=20, ha="right", fontsize=8)
plt.tight_layout()
plt.savefig("wiki/assets/meta-ad-fraud-chart.png", dpi=150)
